namespace: vegetable-ns

image:
  repository: aryankollurishetty/vegetable-app
  tag: v1.0

deployment:
  name: vegetable
  replicas: 1
  port: 3000
  labels:
    app: vegetable

service:
  name: vegetable-service
  type: LoadBalancer
  port: 80
  targetPort: 3000
  labels:
    app: vegetable

config:
  mongodbUri: mongodb://mongodb:27017/vegetable
  mongoInitDb: vegetable

mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: latest
  replicas: 1
  port: 27017
  labels:
    app: mongodb

storage:
  className: vegetable-sc
  type: gp3
  size: 1Gi
