apiVersion: v1
kind: Service
metadata:
  name: vegetable-service
  namespace: vegetable-ns
spec:
  type: LoadBalancer
  selector:
    app: vegetable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

